include 'bi_div_128_64.inc'

include 'bi_rem_128_64.inc'
include 'bi_rem_128_128.inc'

include 'bi_rem_192_64.inc'
include 'bi_rem_192_128.inc'

include 'bi_rem_256_64.inc'
include 'bi_rem_256_128.inc'

include 'bi_rem_512_64.inc'
include 'bi_rem_512_128.inc'
include 'bi_rem_512_256.inc'

include 'bi_div_rem_128_64.inc'
include 'bi_div_rem_128_128.inc'

include 'bi_div_rem_192_64.inc'
include 'bi_div_rem_192_128.inc'
include 'bi_div_rem_192_192.inc'

include 'bi_div_rem_256_64.inc'
include 'bi_div_rem_256_128.inc'
include 'bi_div_rem_256_256.inc'
include 'bi_div_rem_512_64.inc'
include 'bi_div_rem_512_128.inc'
include 'bi_div_rem_512_256.inc'
include 'bi_div_rem_512_512.inc'
