if ~ definite bi_cmp_index

bi_cmp_index equ 0

include 'bi_cmp_128_128.inc'
include 'bi_cmp_192_128.inc'
include 'bi_cmp_192_192.inc'
include 'bi_cmp_256_128.inc'
include 'bi_cmp_256_192.inc'
include 'bi_cmp_256_256.inc'
include 'bi_cmp_320_128.inc'
include 'bi_cmp_320_192.inc'
include 'bi_cmp_320_256.inc'
include 'bi_cmp_320_320.inc'
include 'bi_cmp_384_128.inc'
include 'bi_cmp_384_192.inc'
include 'bi_cmp_384_256.inc'
include 'bi_cmp_384_320.inc'
include 'bi_cmp_384_384.inc'
include 'bi_cmp_448_128.inc'
include 'bi_cmp_448_320.inc'
include 'bi_cmp_448_384.inc'
include 'bi_cmp_448_448.inc'
include 'bi_cmp_512_128.inc'
include 'bi_cmp_512_256.inc'
include 'bi_cmp_512_320.inc'
include 'bi_cmp_512_384.inc'
include 'bi_cmp_512_512.inc'
include 'bi_cmp_576_576.inc'
include 'bi_cmp_768_768.inc'
include 'bi_cmp_1024_1024.inc'

end if