include 'bi_mul_64_64.inc'

include 'bi_mul_128_64.inc'
include 'bi_mul_128_128.inc'

include 'bi_mul_192_64.inc'

include 'bi_mul_256_64.inc'
include 'bi_mul_256_128.inc'
include 'bi_mul_256_256.inc'

include 'bi_mul_320_64.inc'

include 'bi_mul_384_64.inc'

include 'bi_mul_448_64.inc'
include 'bi_mul_448_128.inc'

include 'bi_mul_512_64.inc'
include 'bi_mul_512_256.inc'
include 'bi_mul_512_512.inc'
